-- Schema PostgreSQL (producción, por ejemplo Neon).
-- Ejecutar una vez sobre la base vacía.

DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS alert_rules;
DROP TABLE IF EXISTS measurements;
DROP TABLE IF EXISTS formulas;
DROP TABLE IF EXISTS sensor_variables;
DROP TABLE IF EXISTS sensors;

CREATE TABLE sensors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  api_key VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_sensors_api_key ON sensors (api_key);
CREATE INDEX idx_sensors_name ON sensors (name);

CREATE TABLE sensor_variables (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id INTEGER NOT NULL REFERENCES sensors (id) ON DELETE CASCADE,
  name VARCHAR(80) NOT NULL,
  type VARCHAR(20) NOT NULL DEFAULT 'measure' CHECK (type IN ('measure', 'calculated')),
  unit VARCHAR(20) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (sensor_id, name)
);

CREATE INDEX idx_sensor_variables_sensor_id ON sensor_variables (sensor_id);

CREATE TABLE formulas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id INTEGER NOT NULL REFERENCES sensors (id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  expression TEXT NOT NULL,
  result_variable_id INTEGER NOT NULL REFERENCES sensor_variables (id) ON DELETE CASCADE,
  parameters JSONB NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_formulas_sensor_id ON formulas (sensor_id);
CREATE INDEX idx_formulas_result_variable_id ON formulas (result_variable_id);

CREATE TABLE measurements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id INTEGER NOT NULL REFERENCES sensors (id) ON DELETE CASCADE,
  variable_id INTEGER NOT NULL REFERENCES sensor_variables (id) ON DELETE CASCADE,
  value NUMERIC(20, 6) NOT NULL,
  measured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_measurements_sensor_id ON measurements (sensor_id);
CREATE INDEX idx_measurements_variable_id ON measurements (variable_id);
CREATE INDEX idx_measurements_measured_at ON measurements (measured_at);
CREATE INDEX idx_measurements_sensor_measured ON measurements (sensor_id, measured_at);

CREATE TABLE alert_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id INTEGER NOT NULL REFERENCES sensors (id) ON DELETE CASCADE,
  variable_id INTEGER NOT NULL REFERENCES sensor_variables (id) ON DELETE CASCADE,
  operator VARCHAR(5) NOT NULL CHECK (operator IN ('>', '<', '>=', '<=', '=')),
  threshold_value NUMERIC(20, 6) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  is_active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_alert_rules_sensor_id ON alert_rules (sensor_id);
CREATE INDEX idx_alert_rules_variable_id ON alert_rules (variable_id);

CREATE TABLE alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_rule_id INTEGER NOT NULL REFERENCES alert_rules (id) ON DELETE CASCADE,
  sensor_id INTEGER NOT NULL REFERENCES sensors (id) ON DELETE CASCADE,
  variable_id INTEGER NOT NULL REFERENCES sensor_variables (id) ON DELETE CASCADE,
  value NUMERIC(20, 6) NOT NULL,
  threshold_value NUMERIC(20, 6) NOT NULL,
  operator VARCHAR(5) NOT NULL,
  message VARCHAR(500) DEFAULT NULL,
  triggered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_alerts_alert_rule_id ON alerts (alert_rule_id);
CREATE INDEX idx_alerts_sensor_id ON alerts (sensor_id);
CREATE INDEX idx_alerts_triggered_at ON alerts (triggered_at);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sensors_set_updated_at
  BEFORE UPDATE ON sensors
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER sensor_variables_set_updated_at
  BEFORE UPDATE ON sensor_variables
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER formulas_set_updated_at
  BEFORE UPDATE ON formulas
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER alert_rules_set_updated_at
  BEFORE UPDATE ON alert_rules
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
